// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNivug0gwkZlNqncbvMwLWJTbJfYT-n-8',
    appId: '1:760583748659:web:fcc2ceee2fc595143d3746',
    messagingSenderId: '760583748659',
    projectId: 'happytomato-591f9',
    authDomain: 'happytomato-591f9.firebaseapp.com',
    storageBucket: 'happytomato-591f9.appspot.com',
    measurementId: 'G-PSRRVXGY69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPbTu45FYasp-YhmW53zit5ky91z_dNdQ',
    appId: '1:760583748659:android:781ad28c05c5ea853d3746',
    messagingSenderId: '760583748659',
    projectId: 'happytomato-591f9',
    storageBucket: 'happytomato-591f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYYcV2a5vMJK0o6fosbiIiQD3eUQEnAlE',
    appId: '1:760583748659:ios:24a955050af7327f3d3746',
    messagingSenderId: '760583748659',
    projectId: 'happytomato-591f9',
    storageBucket: 'happytomato-591f9.appspot.com',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYYcV2a5vMJK0o6fosbiIiQD3eUQEnAlE',
    appId: '1:760583748659:ios:b97bd3d33366bb4b3d3746',
    messagingSenderId: '760583748659',
    projectId: 'happytomato-591f9',
    storageBucket: 'happytomato-591f9.appspot.com',
    iosBundleId: 'com.example.testapp.RunnerTests',
  );
}
